core/urls.py
from django.contrib import admin
from django.urls import path, include
from user_profile.views import login_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_view, name='login'),
    path('th_monitoring/', include('th_monitoring.urls', namespace='th_monitoring')),
    path('user_profile/', include(('user_profile.urls', 'user_profile'), namespace='user_profile')),


]

th_monitoring/urls.py
# th_monitoring/urls.py

from django.urls import path
from . import views

app_name = 'th_monitoring'

urlpatterns = [ 
    path('dashboard/', views.dashboard_view, name='dashboard'),  # Make sure name matches
    path('dashboard/trend_page/', views.trend_page, name='trend_page'),
    path('email-settings/', views.email_settings, name='email_settings'),

]

th_monitoring/models.py
from django.db import models

class BaseMonitoringData(models.Model):
    date = models.DateField()
    time = models.TimeField()
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    humidity = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        abstract = True  # This makes the model abstract, so it won't create a separate table

class QecData(BaseMonitoringData):
    pass  # Inherits everything from BaseMonitoringData

    def __str__(self):
        return f"QEC data on {self.date} at {self.time}"

class QtaData(BaseMonitoringData):
    pass  # Inherits everything from BaseMonitoringData

    def __str__(self):
        return f"QTA data on {self.date} at {self.time}"

class QscData(BaseMonitoringData):
    pass  # Inherits everything from BaseMonitoringData

    def __str__(self):
        return f"QSC data on {self.date} at {self.time}"


class EmailSettings(models.Model):
    sender_email = models.EmailField(max_length=254)
    receiver_email = models.EmailField(max_length=254)
    password = models.CharField(max_length=50)  # Consider encrypting this field for security

    def __str__(self):
        return "Email Settings"

th_monitoring/forms.py
from django import forms
from .models import EmailSettings

class EmailSettingsForm(forms.ModelForm):
    class Meta:
        model = EmailSettings
        fields = ['sender_email', 'receiver_email', 'password']

th_monitoring/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from datetime import datetime, timedelta
from django.utils import timezone
from .models import QecData, QtaData, QscData
from .forms import EmailSettingsForm
from django.core.exceptions import ObjectDoesNotExist

def dashboard_view(request):
    # Mapping of categories to their respective models
    model_mapping = {
        'qec': QecData,
        'qta': QtaData,
        'qsc': QscData,
    }
    
    latest_data = {}
    
    for category, model in model_mapping.items():
        try:
            # Attempt to get the latest entry by the highest ID
            latest_entry = model.objects.latest('id')
            
            # If successful, store the relevant data in the dictionary
            latest_data[category] = {
                'date': latest_entry.date,
                'time': latest_entry.time,
                'temperature': latest_entry.temperature,
                'humidity': latest_entry.humidity,
            }
        except ObjectDoesNotExist:
            # Handle the case where no entries exist for the model
            latest_data[category] = 'No data available'
    
    context = {'latest_data': latest_data, 'show_navbar': True}
    
    return render(request, 'th_monitoring/dashboard.html', context)


def trend_page(request):
    # Category mapping to model classes
    model_map = {
        'qec': QecData,
        'qta': QtaData,
        'qsc': QscData,
    }
    
    # Calculate dates for the last month
    end_date = timezone.now().date()
    start_date = end_date - timedelta(days=30)
    
    # Format dates for the input fields
    default_end_date = end_date.strftime('%Y-%m-%d')
    default_start_date = start_date.strftime('%Y-%m-%d')
    
    # Get category and dates from GET request or use defaults
    category = request.GET.get('category', 'qsc').lower()  # Default to 'qsc' if not provided
    selected_start_date = request.GET.get('start_date', default_start_date)
    selected_end_date = request.GET.get('end_date', default_end_date)

    # Validate category
    if category not in model_map:
        return render(request, 'error_page.html', {'error': 'Invalid category specified'})

    # Get the model based on the category
    model = model_map[category]

    # Fetch data from the model based on the selected date range
    data = model.objects.filter(
        date__gte=selected_start_date,
        date__lte=selected_end_date
    ).order_by('-date', '-time')

    context = {
        'category': category.upper(),
        'data': data,
        'start_date': selected_start_date,
        'end_date': selected_end_date,
        'show_navbar': True
    }

    return render(request, 'th_monitoring/trend_page.html', context)

def email_settings(request):
    if request.method == "POST":
        form = EmailSettingsForm(request.POST)
        if form.is_valid():
            form.save()
            # Ensure you have a URL named 'success_url' defined in your urls.py, or change this to an appropriate redirect.
            return redirect('th_monitoring:dashboard')  # Example: redirecting to the dashboard after saving.
    else:
        form = EmailSettingsForm()
    
    # Adjusted the template path to include the app name as a namespace.
    return render(request, 'th_monitoring/email_settings.html', {'form': form, 'show_navbar': True})

th_monitoring/templates/th_monitoring/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block title %}Dashboard{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

<div class="dashboard-container">
    <div class="container">
        <div class="row justify-content-center">
            {% for category, data in latest_data.items %}
                <div class="col-md-4 mb-4">
                    <a href="{% url 'th_monitoring:trend_page' %}?category={{ category }}" class="card-link">
                        <div class="card h-100" data-category="{{ category|lower }}">
                            <div class="card-header">
                                {{ category|capfirst }} Server Room
                            </div>
                            <div class="card-body">
                                <div class="card-section top-row"> <!-- Group for the top row with date and time -->
                                    <div class="icon-group">
                                        <i class="fas fa-calendar-alt icon-color-date"></i>
                                        <p>{{ data.date|date:"SHORT_DATE_FORMAT" }}</p>
                                    </div>
                                    <div class="icon-group">
                                        <i class="fas fa-clock icon-color-time"></i>
                                        <p>{{ data.time }}</p>
                                    </div>
                                </div>
                                <div class="card-section bottom-row"> <!-- Group for the bottom row with temperature and humidity -->
                                    <div class="icon-group">
                                        <i class="fas fa-temperature-low icon-color-temp"></i>
                                        <p>{{ data.temperature }}°C</p>
                                    </div>
                                    <div class="icon-group">
                                        <i class="fas fa-tint icon-color-humid"></i>
                                        <p>{{ data.humidity }}%</p>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

th_monitoring/templates/th_monitoring/email_settings.html
{% extends "base.html" %}

{% block title %}Email Settings{% endblock %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/email_alerts.css' %}">
<div class="email_settings-container">
    <div class="email_settings-card">
        <h2 class="email_settings-title">Email Settings</h2>
        <form method="post" class="email_settings-form">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <input type="{{ field.field.widget.input_type }}" 
                       name="{{ field.name }}" 
                       class="form-field {{ field.css_classes }}" 
                       placeholder="{{ field.label }}" 
                       id="id_{{ field.name }}"
                       {% if field.field.required %}required{% endif %}>
            </div>
            {% endfor %}
            <button type="submit" class="email_settings-btn">Save</button>
            <a href="{% url 'th_monitoring:dashboard' %}" class="btn btn-secondary btn-block">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

th_monitoring/templates/th_monitoring/trend_page.html
{% extends "base.html" %}

{% block title %}Trends{% endblock %}

{% load static %}  <!-- Load the tag library -->

{% block content %}

<link rel="stylesheet" href="{% static 'css/trends.css' %}">

<div class="trends-container">
    <div class="centered-content">
        <h1 class="text-center mb-4">Trends for {{ category }}</h1>
        
        <form class="form-inline my-3" action="" method="get">
            <input type="hidden" name="category" value="{{ category }}">
            <div class="form-group mx-sm-3">
                <label for="start_date" class="sr-only">Start Date</label>
                <input type="date" class="form-control" id="start_date" name="start_date" value="{{ start_date }}">
            </div>
            <div class="form-group mx-sm-3">
                <label for="end_date" class="sr-only">End Date</label>
                <input type="date" class="form-control" id="end_date" name="end_date" value="{{ end_date }}">
            </div>
            <button type="submit" class="btn-refresh ">
                <i class="fas fa-sync-alt"></i> Update
            </button>
            <a href="http://localhost:8000/th_monitoring/dashboard/" class="btn-dashboard">
                <i class="fas fa-tachometer-alt"></i> Dashboard
            </a>
        </form>

        {% if data %}
            <div class="chart-container">
                <canvas id="dataChart"></canvas>
            </div>
        {% else %}
            <div class="alert alert-warning" role="alert">
                No data available.
            </div>
        {% endif %}
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var ctx = document.getElementById('dataChart').getContext('2d');
        var chartData = {
            labels: [],
            datasets: [{
                label: 'Temperature (°C)',
                data: [],
                borderColor: 'rgba(255, 99, 132, 1)',
                fill: false
            }, {
                label: 'Humidity (%)',
                data: [],
                borderColor: 'rgba(54, 162, 235, 1)',
                fill: false
            }]
        };
    
        {% for item in data %}
            chartData.labels.push("{{ item.date }}");
            chartData.datasets[0].data.push({{ item.temperature }});
            chartData.datasets[1].data.push({{ item.humidity }});
        {% endfor %}
    
        var dataChart = new Chart(ctx, {
            type: 'line',
            data: chartData,
            options: {
                scales: {
                    y: {
                        beginAtZero: false
                    }
                },
                responsive: true,
                maintainAspectRatio: false
            }
        });
    });
    </script>
    
{% endblock %}